/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fraIndex.java
 *
 * Created on 27/06/2010, 05:30:07 PM
 */

package firstfollow;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author usuario
 */
public class fraIndex extends javax.swing.JFrame {
    //variables y controles a utilizar
    public JTabbedPane jtpEditor;
    private Recursividad recursividad;
    private Factorizacion factorizar;
    private Editor editor;

    /** Creates new form fraIndex */
    public fraIndex() {
        //-------------
        editor=new Editor(this);
        initComponents();
        //*************
        jtpEditor=jtpEditor_;
        this.setLocationRelativeTo(null); //centrar pantalla
        jbAmbiguedad.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpOpciones = new javax.swing.JPanel();
        jbAnalizar = new javax.swing.JButton();
        jbRecursividad = new javax.swing.JButton();
        jbFactorizacion = new javax.swing.JButton();
        jbPrimeros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpSimbolos = new javax.swing.JPanel();
        jbVacio = new javax.swing.JButton();
        jbFlecha = new javax.swing.JButton();
        jpSeparador = new javax.swing.JButton();
        jbPuntoComa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbAmbiguedad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbSiguientes = new javax.swing.JButton();
        jbPredictivo = new javax.swing.JButton();
        jbTablaM = new javax.swing.JButton();
        jbSimulacion = new javax.swing.JButton();
        jbCondicionLL1 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jbNuevo = new javax.swing.JButton();
        jbAbrir = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jtpEditor_ = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("First Follow – Verificador de gramáticas LL1");

        jpOpciones.setBackground(new java.awt.Color(204, 204, 204));

        jbAnalizar.setText("Analizar Gramática ");
        jbAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAnalizarMouseClicked(evt);
            }
        });

        jbRecursividad.setText("Eliminar Recursividad ");
        jbRecursividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRecursividadMouseClicked(evt);
            }
        });

        jbFactorizacion.setText("Factorización Izquierda");
        jbFactorizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFactorizacionMouseClicked(evt);
            }
        });

        jbPrimeros.setText("Primeros");
        jbPrimeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPrimerosMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("--Opciones--");

        jbVacio.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbVacio.setText("€");
        jbVacio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVacioMouseClicked(evt);
            }
        });

        jbFlecha.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbFlecha.setText("-->");
        jbFlecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFlechaMouseClicked(evt);
            }
        });

        jpSeparador.setFont(new java.awt.Font("Tahoma", 1, 12));
        jpSeparador.setText("|");
        jpSeparador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpSeparadorMouseClicked(evt);
            }
        });

        jbPuntoComa.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbPuntoComa.setText(";");
        jbPuntoComa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPuntoComaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Símbolos ");

        javax.swing.GroupLayout jpSimbolosLayout = new javax.swing.GroupLayout(jpSimbolos);
        jpSimbolos.setLayout(jpSimbolosLayout);
        jpSimbolosLayout.setHorizontalGroup(
            jpSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSimbolosLayout.createSequentialGroup()
                .addGroup(jpSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSimbolosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbFlecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpSimbolosLayout.createSequentialGroup()
                                    .addComponent(jbVacio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jpSeparador)))
                            .addComponent(jbPuntoComa)))
                    .addGroup(jpSimbolosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpSimbolosLayout.setVerticalGroup(
            jpSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSimbolosLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSimbolosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVacio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFlecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPuntoComa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbAmbiguedad.setText("Ambigüedad");
        jbAmbiguedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAmbiguedadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jbSiguientes.setText("Siguientes");
        jbSiguientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSiguientesMouseClicked(evt);
            }
        });

        jbPredictivo.setText("Predictivo");
        jbPredictivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPredictivoMouseClicked(evt);
            }
        });

        jbTablaM.setText("Tabla M");
        jbTablaM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTablaMMouseClicked(evt);
            }
        });

        jbSimulacion.setText("Simulación");
        jbSimulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSimulacionMouseClicked(evt);
            }
        });

        jbCondicionLL1.setText("Condición LL(1)");
        jbCondicionLL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCondicionLL1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpOpcionesLayout = new javax.swing.GroupLayout(jpOpciones);
        jpOpciones.setLayout(jpOpcionesLayout);
        jpOpcionesLayout.setHorizontalGroup(
            jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOpcionesLayout.createSequentialGroup()
                .addGroup(jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addComponent(jpSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpOpcionesLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAnalizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jbRecursividad, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jbFactorizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAmbiguedad, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbPrimeros, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbSiguientes, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbPredictivo, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbCondicionLL1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbTablaM, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jpOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpOpcionesLayout.setVerticalGroup(
            jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAnalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRecursividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFactorizacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAmbiguedad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPrimeros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSiguientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPredictivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCondicionLL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTablaM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSimulacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar2.setRollover(true);

        jbNuevo.setText("Nuevo");
        jbNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNuevoMouseClicked(evt);
            }
        });

        jbAbrir.setText("Abrir");
        jbAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAbrirMouseClicked(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbGuardarMouseClicked(evt);
            }
        });

        jbCerrar.setText("Cerrar");
        jbCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNuevo)
                .addGap(18, 18, 18)
                .addComponent(jbAbrir)
                .addGap(26, 26, 26)
                .addComponent(jbGuardar)
                .addGap(126, 126, 126)
                .addComponent(jbCerrar)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbAbrir)
                    .addComponent(jbGuardar)
                    .addComponent(jbCerrar))
                .addContainerGap())
        );

        jToolBar3.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar3.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtpEditor_, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtpEditor_)
                    .addComponent(jpOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(633, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevoMouseClicked
        editor.nuevo();
        editor.compilarGramatica();
    }//GEN-LAST:event_jbNuevoMouseClicked

    private void jbAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAbrirMouseClicked
        editor.abrir();
        editor.compilarGramatica();
    }//GEN-LAST:event_jbAbrirMouseClicked

    private void jbGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGuardarMouseClicked
        editor.guardar();
    }//GEN-LAST:event_jbGuardarMouseClicked

    private void jbCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarMouseClicked
        editor.cerrar();
    }//GEN-LAST:event_jbCerrarMouseClicked

    private void jbAnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAnalizarMouseClicked
        editor.compilarGramatica();
    }//GEN-LAST:event_jbAnalizarMouseClicked

    private void jbRecursividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRecursividadMouseClicked
        //Eliminar recursividad de la gramática
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){            
            recursividad=new Recursividad(this,gramatica);
            recursividad.load();
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }
    }//GEN-LAST:event_jbRecursividadMouseClicked

    private void jbVacioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVacioMouseClicked
        editor.insertarSimbolo(0);
    }//GEN-LAST:event_jbVacioMouseClicked

    private void jpSeparadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSeparadorMouseClicked
        editor.insertarSimbolo(1);
    }//GEN-LAST:event_jpSeparadorMouseClicked

    private void jbFlechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFlechaMouseClicked
        editor.insertarSimbolo(2);
    }//GEN-LAST:event_jbFlechaMouseClicked

    private void jbPuntoComaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPuntoComaMouseClicked
        editor.insertarSimbolo(3);
    }//GEN-LAST:event_jbPuntoComaMouseClicked

    private void jbFactorizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFactorizacionMouseClicked
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){
            factorizar=new Factorizacion(this,gramatica);
            factorizar.load();
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }
    }//GEN-LAST:event_jbFactorizacionMouseClicked

    private void jbPrimerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPrimerosMouseClicked
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){           
                gramatica.cPrediccion.calcularPrimeros(true);
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }
    }//GEN-LAST:event_jbPrimerosMouseClicked

    private void jbAmbiguedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAmbiguedadMouseClicked
 /*       Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){
                gramatica.ambiguedad.ambiguo.AnalizadorDeAmbiguedad();
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }*/
    }//GEN-LAST:event_jbAmbiguedadMouseClicked

    private void jbSiguientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSiguientesMouseClicked
      
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){
                gramatica.cPrediccion.calcularSiguientes(true);
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }      
    }//GEN-LAST:event_jbSiguientesMouseClicked

    private void jbPredictivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPredictivoMouseClicked
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){
                gramatica.predictivo.CalcularPredictivo(true);
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }
    }//GEN-LAST:event_jbPredictivoMouseClicked

    private void jbTablaMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTablaMMouseClicked
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){
             if(gramatica.cLL.VerificarCondicionLL(1)==true){
                gramatica.tablaM.crearTabla(true);
             }
             else{
                JOptionPane.showMessageDialog(this, " La gramática no es LL(1) ");
             }
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }
    }//GEN-LAST:event_jbTablaMMouseClicked

    private void jbSimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSimulacionMouseClicked
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){
            if(gramatica.cLL.VerificarCondicionLL(1)==true){
                gramatica.simulador.Analizar();
            }
            else
            {
                JOptionPane.showMessageDialog(this, " La gramática no es LL(1) ");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }
    }//GEN-LAST:event_jbSimulacionMouseClicked

    private void jbCondicionLL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCondicionLL1MouseClicked
        Gramatica gramatica=editor.compilarGramatica();
        if(gramatica!=null){
                gramatica.cLL.VerificarCondicionLL(0);
        }
        else{
            JOptionPane.showMessageDialog(this, " Debe corregir errores: Léxico – Sintácticos. ");
        }
    }//GEN-LAST:event_jbCondicionLL1MouseClicked
    public void AplicarCambios(Gramatica ng)
    {
        editor.AplicarCambios(ng);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JButton jbAbrir;
    private javax.swing.JButton jbAmbiguedad;
    private javax.swing.JButton jbAnalizar;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbCondicionLL1;
    private javax.swing.JButton jbFactorizacion;
    private javax.swing.JButton jbFlecha;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbPredictivo;
    private javax.swing.JButton jbPrimeros;
    private javax.swing.JButton jbPuntoComa;
    private javax.swing.JButton jbRecursividad;
    private javax.swing.JButton jbSiguientes;
    private javax.swing.JButton jbSimulacion;
    private javax.swing.JButton jbTablaM;
    private javax.swing.JButton jbVacio;
    private javax.swing.JPanel jpOpciones;
    private javax.swing.JButton jpSeparador;
    private javax.swing.JPanel jpSimbolos;
    private javax.swing.JTabbedPane jtpEditor_;
    // End of variables declaration//GEN-END:variables

}
