/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdAvisos.java
 *
 * Created on 5/07/2010, 02:38:40 PM
 */

package firstfollow;
import javax.swing.*;
import javax.swing.text.html.*;
/**
 *
 * @author Derecha
 */
public class jdAvisos_1 extends javax.swing.JDialog {
    public JEditorPane jepMensajes;
    /** Creates new form jdAvisos */
    public jdAvisos_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jepMensajes=jepMensajes_;
        jepMensajes.setContentType( "text/html" );
        this.setLocationRelativeTo(parent);
    }
      public void Mensaje(String msg)
      {
        HTMLDocument doc=(HTMLDocument) jepMensajes.getDocument();
        HTMLEditorKit kit= (HTMLEditorKit) jepMensajes.getEditorKit();
        try{
            //doc.insertString(doc.getLength(), msg+" <br> ", null);
            kit.insertHTML(doc,doc.getLength(),"<b>"+msg+" <br></b> ", 0, 0, HTML.Tag.B);
        }
        catch(Exception be){
            be.printStackTrace();
        }

      }
      public void Mensaje(String titulo, String Error)
      {
        HTMLDocument doc=(HTMLDocument) jepMensajes.getDocument();
        HTMLEditorKit kit= (HTMLEditorKit) jepMensajes.getEditorKit();
        try{
            //doc.insertString(doc.getLength(), msg, null);
            kit.insertHTML(doc,doc.getLength(),"<b>"+titulo+"</b><font color=\"red\">"+Error+"</font><br>", 0, 0, HTML.Tag.B);
            //doc.insertString(doc.getLength(), "\n", null);
        }
        catch(Exception be){
            be.printStackTrace();
        }
      }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jToolBar2 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepMensajes_ = new javax.swing.JEditorPane();
        jbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mensajes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jToolBar1.setRollover(true);

        jToolBar2.setRollover(true);

        jepMensajes_.setEditable(false);
        jScrollPane1.setViewportView(jepMensajes_);

        jbAceptar.setText("Aceptar");
        jbAceptar.setFocusable(false);
        jbAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAceptarMouseClicked
        this.hide();
    }//GEN-LAST:event_jbAceptarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JEditorPane jepMensajes_;
    // End of variables declaration//GEN-END:variables

}
