/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Simulador.java
 *
 * Created on 21/08/2010, 04:30:19 PM
 */

package firstfollow;
import javax.swing.*;
/**
 *
 * @author Derecha
 */
public class jdSimulador extends javax.swing.JDialog {
    public JTextField textCadena;
    public JEditorPane jepMensajes;
    public JScrollPane jspTabla;
    private Simulador sim;
    /** Creates new form Simulador */
    public jdSimulador(java.awt.Frame parent, boolean modal,Simulador sim) {
        super(parent, modal);
        initComponents();
        textCadena=this.textCadena_;
        jepMensajes=this.jepMensajes_;
        jspTabla=this.jspTabla_;
        jepMensajes.setContentType("text/html");
        this.sim=sim;
    }
    public void insertarTabla(JTable tabla)
    {
        jspTabla.setViewportView(tabla);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jspTabla_ = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        textCadena_ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbAnalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepMensajes_ = new javax.swing.JEditorPane();
        jbAceptar = new javax.swing.JButton();
        jbGenerarArbol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane2.setDividerLocation(240);
        jSplitPane2.setDividerSize(10);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspTabla_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspTabla_, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel3);

        textCadena_.setFont(new java.awt.Font("Tahoma", 1, 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Cadena de entrada:");

        jbAnalizar.setFont(new java.awt.Font("Tahoma", 1, 14));
        jbAnalizar.setText("Análizar ");
        jbAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAnalizarMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jepMensajes_);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(jbAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCadena_, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textCadena_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jbAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel1);

        jbAceptar.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbAceptar.setText("Aceptar");
        jbAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAceptarMouseClicked(evt);
            }
        });

        jbGenerarArbol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbGenerarArbol.setText("Crear Árbol");
        jbGenerarArbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbGenerarArbolMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbGenerarArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 592, Short.MAX_VALUE)
                        .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGenerarArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAnalizarMouseClicked
        jepMensajes_.setText("");
        sim.Calcular();
    }//GEN-LAST:event_jbAnalizarMouseClicked

    private void jbAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAceptarMouseClicked
        this.hide();
    }//GEN-LAST:event_jbAceptarMouseClicked

    private void jbGenerarArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGenerarArbolMouseClicked

    }//GEN-LAST:event_jbGenerarArbolMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbAnalizar;
    private javax.swing.JButton jbGenerarArbol;
    private javax.swing.JEditorPane jepMensajes_;
    private javax.swing.JScrollPane jspTabla_;
    private javax.swing.JTextField textCadena_;
    // End of variables declaration//GEN-END:variables

}
